### PR TITLE
On mobile devices the keyboard is shown and hides when clicking on a nested form input

### PR DESCRIPTION
**Pull request by luke-venn-ft**
The 'populateMoreList' was being called in the 'resize' handler regardless of whether the list had changed. This meant that any nested form inputs would be removed which, on mobile, also removed the on screen keyboard making entry impossible. Moving it to the 'oSquishyList.change' handler means that it will only be called when required which leads to avoiding unnecessary re-draws as well as fixing the bug. This is using v2.x but is probably applicable to the current version too.

### CODE REVIEW

**Comment by AlbertoElias** [comment]
There are linting errors and I think the spacing is not correct

**Comment by luke-venn-ft** [comment]
I've amended to use tabs but I think the other linting errors are from using var but since it's a fix for 2.x I believe this should be correct.

**Comment by AlbertoElias** [comment]
It's missing 'use strict' errors

**Comment by luke-venn-ft** [comment]
I've not changed any of that but I can tidy up if you'd like

**Pull request merged**
